# === Stage 1: Build stage ===
FROM node:24-slim AS build

# Set Working directory
WORKDIR /app

# Copy dependency requirements
COPY package*.json .

# Install dependencies
RUN npm ci

# Copy app source
COPY . .

# Build source code
RUN npm run build


# === Stage 2: Production stage ===
FROM node:24-slim AS production

# Set Working directory
WORKDIR /app

# Copy dependency requirements
COPY package*.json .

# Install production dependencies
RUN npm ci --only=production

# Copy source code from Build stage
COPY --from=build ./app/.next .next

# Copy source code
COPY . .

# Expose port 
EXPOSE 3000

# Run app 
CMD [ "npm", "start" ]