name: ShopNexus

services:
  prometheus:
    image: bitnami/prometheus:3.4.0
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/opt/bitnami/prometheus/data
      - ./observability/monitoring/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - shopnexus-net
      - monitoring
  node-exporter:
    image: bitnami/node-exporter:1.9.1
    networks:
      - shopnexus-net
      - monitoring
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - shopnexus-net
      - monitoring
      
  grafana:
    image: grafana/grafana:12.0.0
    env_file:
      - ./observability/monitoring/grafana/.env
    ports:
      - 3001:3001
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./observability/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./observability/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file:
      - ./observability/logging/elasticsearch/.env
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - logging

  fluent-bit:
    image: fluent/fluent-bit:1.9
    user: root
    volumes:
      - ./observability/logging/fluentbit/conf:/fluent-bit/etc
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - shopnexus-net
      - logging
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    env_file:
      - ./observability/logging/kibana/.env  
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
      - ./observability/logging/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - logging
    depends_on:
      - elasticsearch  

volumes:
  prometheus-data:
  fluet_bit-logs:
  grafana-data:
  elasticsearch-data:
  kibana-data:

networks:
  monitoring:
  logging:
  shopnexus-net: