name: Checkout & Setup Environment

description: >
  Composite action to checkout code, set up Node or Python environment,
  and cache dependencies.

inputs:
  working-directory:
    required: true
    description: The working directory of your file 

  environment:
    required: true
    description: The environment type ("node" or "python")

  path:
    required: true
    description: The cache path for dependencies

  key:
    required: true
    description: The file(s) used to generate the cache key


runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Node Environment
      if: inputs.environment == "node"
      uses: actions/setup-node@v4
      with:
        node-version: 23.x 

    - name: Python Environment
      if: inputs.environment != 'node'
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}
        key: ${{ runner.os }}-${{ inputs.environment }}-${{ hashFiles(inputs.key) }}-${{ inputs.working-directory }}

    - name: Install Node Dependencies
      if: inputs.environment == 'node'
      shell: bash
      run: npm install

    - name: Install Python Dependencies
      working-directory: ${{ inputs.working-directory }}
      if: inputs.environment != 'node'
      shell: bash
      run: pip install --no-cache-dir --target=./install -r requirements.txt

  