{
 "title": "Microservices Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{job=~\"user-service|product-service\"}[5m])",
     "legendFormat": "{{job}} - {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{job=~\"user-service|product-service\"}[5m]) / rate(flask_http_request_duration_seconds_count{job=~\"user-service|product-service\"}[5m])",
     "legendFormat": "{{job}} - {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{job=~\"user-service|product-service\",status=~\"4..|5..\"}[5m])) / sum(rate(flask_http_request_total{job=~\"user-service|product-service\"}[5m])) * 100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "flask_http_request_total{job=~\"user-service|product-service\"}",
     "legendFormat": "{{job}} - {{method}} {{path}}"
    }
   ]
  }
 ]
}