name: Frontend CI

on: 
    push:
        paths: 
            - /frontend
    workflow_dispatch:


jobs:
    frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Checkout & Setup
              uses: ./.github/actions/setup-env
              with:
                working-directory: frontend
                environment: node
                path: node_modules
                key: package-lock.json

            - name: Run Unit Test
              working-directory: frontend
              run: npm run test

