name: Product-service CI

on: 
    push:
        paths: 
            - ./product-service
    workflow_dispatch:


jobs:
    product-service:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Checkout & Setup
              uses: ./.github/actions/setup-env
              with:
                working-directory: product-service
                environment: python
                path: ./install
                key: requirements.txt

            - name: Run Unit Test
              working-directory: product-service
              run:  python -m unittest tests/test_app.py

